volumes:
  data:
  scripts:
  db:

networks:
  piwigo:
    driver: bridge
    ipam:
      config:
        - subnet: '${PROJECT_SUBNET}'
    driver_opts:
      com.docker.network.bridge.name: piwigo_net
  REVERSE_PROXY:
    external: true

services:
  piwigo:
    image: piwigo/piwigo:${PIWIGO_VERSION:-latest}
    hostname: piwigo
    container_name: piwigo
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=REVERSE_PROXY"
      - "traefik.http.routers.${PROJECT}.rule=Host(`${PROJECT_FQDN}`)"
      - "traefik.http.routers.${PROJECT}.entrypoints=${PROJECT_ENTRYPOINT}"
      - "traefik.http.routers.${PROJECT}.tls.certresolver=${PROJECT_CERT_RESOLVER}"
      - "traefik.http.routers.${PROJECT}.tls.domains[0].main=${PROJECT_DOMAIN_MAIN}"
      - "traefik.http.routers.${PROJECT}.tls.domains[0].sans=${PROJECT_DOMAIN_SANS}"
      - "traefik.http.services.${PROJECT}.loadbalancer.server.port=80"
    restart: always
    pull_policy: always
    build:
      context: ./src
      dockerfile: Dockerfile
      args:
        DEPLOY_ENV: "production"
        PHP_VERSION: "84"
        PIWIGO_VERSION: "${PIWIGO_VERSION}"
    environment:
      - TZ=${TZ:-Europe/Amsterdam}
    networks:
      - piwigo
      - REVERSE_PROXY
    ports:
      - '${PROJECT_IP:-0.0.0.0}:${PROJECT_PORT:-80}:80'
    depends_on:
      - piwigo.db
    volumes:
      - data:/var/www/html/piwigo/
      - scripts:/usr/local/bin/scripts/

  piwigo.db:
    image: mariadb:${MARIADB_VERSION:-lts}
    hostname: db
    container_name: piwigo.db
    restart: always
    environment:
      - MARIADB_RANDOM_ROOT_PASSWORD=${MARIADB_RANDOM_ROOT_PASSWORD:-true}
      - MARIADB_USER=${MARIADB_USER:-piwigodb_user}
      - MARIADB_DATABASE=${MARIADB_DATABASE:-piwigodb}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD} 
      - TZ=${TZ:-Europe/Amsterdam}
    networks:
      - piwigo
    volumes:
      - db:/var/lib/mysql
